### ISSUE TITLE
Neue Methoden ausdenken

### ISSUE THREAD

**Issue by rfreybe** [fh-erfurt/bord-festival#4]
was auch immer, wenns ins System passt ist gut

**Comment by ddepta** [comment]
Methoden:

Client
getTickets() um alle Tickets eines Kundes zu bekommen

LineUp
moveBand(Band, TimeSlot) um Slot einer Band zu verschieben

Band
getPricePerEvent()

**Comment by ddepta** [comment]
Methoden stehen hier im Kommentar, hab auch noch das Klassendiagramm aktualisiert
